apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: wordpress-ns
type: Opaque
data:
  # Password: "wordpress123" (base64 encoded)
  # echo -n 'wordpress123' | base64
  mysql-root-password: d29yZHByZXNzMTIz
  mysql-password: d29yZHByZXNzMTIz
