apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: wordpress-ns
  labels:
    app: wordpress
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    # NodePort: 30080 (isteğe bağlı - belirtmezseniz otomatik atanır)
    nodePort: 30080
  selector:
    app: wordpress
    tier: frontend
